version: "3.9"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mongodbgame
    environment:
      - MONGO_URI=mongodb://mongodbgame:27023/MongoDbGame
    command: npm run start

  mongodbgame:
    image: mongo:latest
    container_name: mongoDbGame
    restart: always
    ports:
      - "27023:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
